<?php
// =============================================================================
// Metaboxes for acf
// =============================================================================

/**
 * Changes / additions
 * v3.2.0
 * added logo_background_color
 */

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_562a42c357fd3',
	'title' => 'Affiliate fields',
	'fields' => array (
		array (
			'key' => 'field_56a9da2f1acaf',
			'label' => 'Review main fields',
			'name' => 'review_main_fields',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_562a457b33100',
			'label' => 'Affiliate link',
			'name' => 'affiliate_link',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'affiliate_links',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
		),
		array (
			'key' => 'field_562a42cf5ee36',
			'label' => 'Bonus promo title',
			'name' => 'bonus_promo_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_595cd78dabd4f',
			'label' => 'Free spins promo text',
			'name' => 'free_spins_promo',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
        ),
		array (
			'key' => 'field_56a9d98b0c9de',
			'label' => 'Review ratings',
			'name' => 'review_ratings',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
        array(
			'key' => 'field_562a44298f5bd',
			'label' => 'Affiliate rating',
			'name' => 'affiliate_rating',
			'type' => 'range',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 1,
			'min' => 1,
			'max' => 5,
			'step' => '0.1',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_56a8906ef8e8e',
			'label' => 'Ratings number base',
			'name' => 'ratings_number_base',
			'type' => 'text',
			'instructions' => 'This is the base number of total ratings. (e.g. Base number is 18 and 2 users rated the review so the total it\'s going to be 20)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 18,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56a89141f8e8f',
			'label' => 'Rating override',
			'name' => 'rating_override',
			'type' => 'true_false',
			'instructions' => 'If you have enabled user ratings but for this specific review you want to show your rating.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_56a9d9bb0c9df',
			'label' => 'Review additional info',
			'name' => 'review_additional_info',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
        array (
            'multiple' => 0,
            'allow_null' => 0,
            'choices' => array (
                '' => 'Default style',
                'style1' => 'Review style1',
                'style2' => 'Review style2',
                'style3' => 'Review style3'
            ),
            'default_value' => array (
                0 => '',
            ),
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'return_format' => 'value',
            'key' => 'field_59d602eb92dba',
            'label' => 'Review style',
            'name' => 'review_style_override',
            'type' => 'select',
            'instructions' => 'Override the default style for this review',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
		array (
			'key' => 'field_562a435735a55',
			'label' => 'Affiliate small info',
			'name' => 'affiliate_small_info',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
        array (
            'key' => 'field_562a7010adf3a',
            'label' => 'Affiliate info list',
            'name' => 'affiliate_info_list',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'min' => '',
            'max' => '',
            'layout' => 'table',
            'button_label' => 'Add Row',
            'sub_fields' => array (
                array (
                    'key' => 'field_562a704dadf3b',
                    'label' => 'Item title',
                    'name' => 'item_title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array (
                    'key' => 'field_562a7068dda03',
                    'label' => 'Item value',
                    'name' => 'item_value',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
            ),
            'collapsed' => '',
        ),

		array (
			'key' => 'field_562a7988de5d2',
			'label' => 'Pros',
			'name' => 'pros',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_562a798fde5d3',
					'label' => 'Item',
					'name' => 'item',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
			'collapsed' => '',
		),
		array (
			'key' => 'field_562a7994de5d4',
			'label' => 'Cons',
			'name' => 'cons',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_562a79a4de5d5',
					'label' => 'Item',
					'name' => 'item',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
			'collapsed' => '',
        ),
        array (
			'key' => 'field_5c9cd0647ddc7',
			'label' => 'Terms and conditions text',
			'name' => 'terms_conditions_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56a9e903da82e',
			'label' => 'Review thumbnails',
			'name' => 'review_thumbnails',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
        ),
        array (
            'default_value' => '',
            'key' => 'field_5e4fa87266506',
            'label' => 'Logo background color',
            'name' => 'logo_background_color',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '20',
                'class' => '',
                'id' => '',
            ),
        ),
		array (
			'key' => 'field_562a6c9d05b37',
			'label' => 'Affiliate thumbnails',
			'name' => 'affiliate_thumbnails',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add image',
			'sub_fields' => array (
				array (
					'key' => 'field_56a9daaf97f6d',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'affiliates',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_562a453b9d26f',
	'title' => 'Affiliate link fields',
	'fields' => array (
		array (
			'key' => 'field_562a4555f1f45',
			'label' => 'Affiliate key',
			'name' => 'affiliate_key',
			'type' => 'text',
			'instructions' => 'This is the name of the affiliate link that appear in the URL.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'affiliate_links',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_562a453b9dor8',
	'title' => 'Affiliate link fields for desktop',
	'fields' => array (
		array (
			'key' => 'field_562a454cf1f44',
			'label' => 'Affiliate link',
			'name' => 'affiliate_link',
			'type' => 'text',
			'instructions' => 'For Desktop, or if the Mobile link is left blank, this is used for Mobile/Tablet as well ',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_57458a3627dad',
			'label' => 'Affiliate onclick',
			'name' => 'affiliate_onclick',
			'type' => 'text',
			'instructions' => 'Execute a JavaScript when affiliate link is clicked. (Below you can find examples for Google Analytics events)<br/><strong>Example Google Analytics Classic :</strong> _gaq.push(["_trackEvent", "Button", "Click", "Casino name"]);<br/><strong>Example Google Analytics universal :</strong> ga("send", "event", "Button", "Click", "Casino Name"); <i>(This version is used in the theme by default)</i>',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'affiliate_links',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_562a453b9djen',
	'title' => 'Affiliate link fields for mobile',
	'fields' => array (
		array (
			'key' => 'field_562a454cfdir8',
			'label' => 'Affiliate link for mobile',
			'name' => 'affiliate_link_mobile',
			'type' => 'text',
			'instructions' => 'If this field is left empty, the affiliate link for desktop is going to be used instead.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_57458a362dirk',
			'label' => 'Affiliate onclick for mobile',
			'name' => 'affiliate_onclick_mobile',
			'type' => 'text',
			'instructions' => 'Execute a JavaScript when affiliate link is clicked on mobile. (Below you can find examples for Google Analytics events)<br/><strong>Example Google Analytics Classic :</strong> _gaq.push(["_trackEvent", "Button", "Click", "Casino name"]);<br/><strong>Example Google Analytics universal :</strong> ga("send", "event", "Button", "Click", "Casino Name"); <i>(This version is used in the theme by default)</i>',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'affiliate_links',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_562a34699ea05',
	'title' => 'Page fields',
	'fields' => array (
		array (
			'sub_fields' => array (
				array (
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'default_value' => '',
					'delay' => 0,
					'key' => 'field_595cb9a3456b6',
					'label' => 'Section content',
					'name' => 'section_content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '100',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'key' => 'field_595cb9b8456b7',
					'label' => 'Background color',
					'name' => 'background_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'key' => 'field_595cb9ce456b8',
					'label' => 'Background image',
					'name' => 'background_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'multiple' => 0,
					'allow_null' => 0,
					'choices' => array (
						'center top' => 'Center Top',
						'center center' => 'Center Center',
						'center bottom' => 'Center Bottom',
						'left top' => 'Left Top',
						'left center' => 'Left Center',
						'left bottom' => 'Left Bottom',
						'right top' => 'Right Top',
						'right center' => 'Right Center',
						'right bottom' => 'Right Bottom',
					),
					'default_value' => array (
					),
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'return_format' => 'value',
					'key' => 'field_595cb9db456b9',
					'label' => 'Background position',
					'name' => 'background_position',
					'type' => 'select',
					'instructions' => 'Horizontal/Vertical',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'multiple' => 0,
					'allow_null' => 0,
					'choices' => array (
						'auto' => 'Auto',
						'cover' => 'Cover',
						'contain' => 'Contain',
					),
					'default_value' => array (
					),
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'return_format' => 'value',
					'key' => 'field_595cc5de64a91',
					'label' => 'Background size',
					'name' => 'background_size',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'multiple' => 0,
					'allow_null' => 0,
					'choices' => array (
						'no-repeat' => 'No repeat',
						'repeat' => 'Repeat',
						'repeat-x' => 'Repeat X',
						'repeat-y' => 'Repeat Y',
					),
					'default_value' => array (
					),
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'return_format' => 'value',
					'key' => 'field_595ce290cbce7',
					'label' => 'Background repeat',
					'name' => 'background_repeat',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'key' => 'field_595cbaadc5ec0',
					'label' => 'Padding Top/Bottom',
					'name' => 'padding_topbottom',
					'type' => 'text',
					'instructions' => 'Default value: 40px',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '25',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'key' => 'field_595f7d4d0ca6c',
					'label' => 'Text color',
					'name' => 'text_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '25',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'key' => 'field_59ef4f6958b4a',
					'label' => 'Margin top',
					'name' => 'margin_top',
					'type' => 'text',
					'instructions' => 'Default value: 0px',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '25',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'key' => 'field_59ef4f5dd5d66',
					'label' => 'Margin bottom',
					'name' => 'margin_bottom',
					'type' => 'text',
					'instructions' => 'Default value: 0px',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '25',
						'class' => '',
						'id' => '',
					),
				),
			),
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Section',
			'collapsed' => '',
			'key' => 'field_595cb978456b5',
			'label' => 'Full width sections',
			'name' => 'full_width_sections',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'key' => 'field_5668137d508fe',
			'label' => 'Show title of the page',
			'name' => 'show_title_top',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '33.33333',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_59ef4fe748375',
			'label' => 'Hide banner top',
			'name' => 'hide_banner_top_override',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '33.33333',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_59ef4fdf269d8',
			'label' => 'Hide banner bottom',
			'name' => 'hide_banner_bottom_override',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '33.33333',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5665707d45909',
	'title' => 'Slider fields',
	'fields' => array (
		array (
			'key' => 'field_5665708edf080',
			'label' => 'Slider images',
			'name' => 'slider_images',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_566570aedf081',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_566571916e453',
					'label' => 'Image vertical alignment',
					'name' => 'image_vertical_alignment',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'left' => 'Left',
						'right' => 'Right',
						'center' => 'Center',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_566572a56e454',
					'label' => 'Image horizontal alignment',
					'name' => 'image_horizontal_alignment',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'left' => 'Left',
						'right' => 'Right',
						'center' => 'Center',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_566570c2df082',
					'label' => 'Slide text',
					'name' => 'slide_text',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 30,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
				array (
					'key' => 'field_566570d3df083',
					'label' => 'Text position',
					'name' => 'text_position',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'Left' => 'Left',
						'Right' => 'Right',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_566570fbdf084',
					'label' => 'Text background',
					'name' => 'text_background',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
                    'default_value' => 0,
                    'ui' => 1,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
				),
			),
		),
		array (
			'key' => 'field_5665760aa4083',
			'label' => 'Slider timeout',
			'name' => 'slider_timeout',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 8000,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'slider',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_562a30e5eeaf9',
	'title' => 'Theme settings',
	'fields' => array (
		array (
			'key' => 'field_57516dd5973a0',
			'label' => 'General',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_562a310756885',
			'label' => 'Page intro',
			'name' => 'page_intro',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'default_value' => '<h1>WELCOME TO POKA THEME!</h1><p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia</p>[search_affiliates_ajax]',
		),
		array (
			'key' => 'field_562a318743fec',
			'label' => 'Google analytics code',
			'name' => 'google_analytics_code',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'UA-XXXXX-X',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_595cf8a742437',
			'label' => 'Youtube link',
			'name' => 'youtube_link',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_562a342fb24bb',
			'label' => 'Facebook link',
			'name' => 'facebook_link',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_562a343ab24bc',
			'label' => 'Twitter link',
			'name' => 'twitter_link',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_562a3441b24bd',
			'label' => 'Instagram link',
			'name' => 'instagram_link',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_562a48ceae737',
			'label' => 'Affiliate Redirect link folder',
			'name' => 'affiliate_redirect_link_folder',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'go',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56619ddd32cd0',
			'label' => 'Footer copyright text',
			'name' => 'footer_copyright_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Copyright &copy; 2019 - pokatheme.com',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_59d244e02eed8',
			'label' => 'Show related articles in posts page',
			'name' => 'show_related_articles_post',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_569caf83bf63b',
			'label' => 'Allow users to comment in posts',
			'name' => 'users_comment_posts',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_56a88e7743a0e',
			'label' => 'Allow users to comment in reviews',
			'name' => 'allow_users_to_comment_in_reviews',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_56a88ee8cf972',
			'label' => 'Allow user rating in reviews',
			'name' => 'allow_user_rating_in_reviews',
			'type' => 'true_false',
			'instructions' => 'If you want to allow logged in users to rate the reviews check this option.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_56a88ee8cdjrp',
			'label' => 'Allow unregistered user rating in reviews',
			'name' => 'allow_unregistered_user_rating_in_reviews',
			'type' => 'true_false',
			'instructions' => 'If you want to allow unregistered users to rate the reviews check this option.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_59f850cb5653d',
			'label' => 'Enable AMP pages in the theme',
			'name' => 'enable_amp_support',
			'type' => 'true_false',
			'instructions' => 'Before enabling this option you must have installed and enabled official AMP plugin (https://wordpress.org/plugins/amp/)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_57516e2659fdc',
			'label' => 'Banners',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57516e57190fb',
			'label' => 'Banner fullwidth top',
			'name' => 'banner_fullwidth_top',
			'type' => 'textarea',
			'instructions' => 'Place here your adv snippet or your Adrotate shortcode.<br/>The available width in desktop mode is 1110px<br/>For "Header Style 1" place the banner inside field "Page intro"',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_59f71ca7e6550',
			'label' => 'Hide banner fullwidth top at post pages',
			'name' => 'hide_banner_top_posts',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_59f71d2d27496',
			'label' => 'Hide banner fullwidth top at review pages',
			'name' => 'hide_banner_top_reviews',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_59f71d492a5fd',
			'label' => 'Hide banner fullwidth top at posts categories',
			'name' => 'hide_banner_top_cat',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_59f71d55e074b',
			'label' => 'Hide banner fullwidth top at reviews categories',
			'name' => 'hide_banner_top_tax',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_57516f89ce11e',
			'label' => 'Banner fullwidth bottom',
			'name' => 'banner_fullwidth_bottom',
			'type' => 'textarea',
			'instructions' => 'Place here your adv snippet or your Adrotate shortcode.<br/>The available width in desktop mode is 1110px',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_59f71d88b880a',
			'label' => 'Hide banner fullwidth top at post pages',
			'name' => 'hide_banner_bottom_posts',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_59f71d9245d68',
			'label' => 'Hide banner fullwidth top at review pages',
			'name' => 'hide_banner_bottom_reviews',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_59f71d9c209d1',
			'label' => 'Hide banner fullwidth top at posts categories',
			'name' => 'hide_banner_bottom_cat',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_59f71da51b92f',
			'label' => 'Hide banner fullwidth top at reviews categories',
			'name' => 'hide_banner_bottom_tax',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
        ),
        array (
			'key' => 'field_5c9ccef602d9b',
			'label' => 'Terms and Conditions',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
        ),
        array (
			'key' => 'field_5c9ccf1a70596',
			'label' => 'Enable "Terms and Conditions" functionality',
			'name' => 'terms_conditions_functionality',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
        ),
        array (
			'key' => 'field_5c9cfdb117517',
			'label' => 'Enable "Terms and Conditions" tooltip',
			'name' => 'terms_conditions_tooltip',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
        ),
        array (
			'key' => 'field_5c9ccf8652b12',
			'label' => 'Text under each affiliate button',
			'name' => 'terms_text_under_button',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Terms & conditions apply',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-general-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5668157f05855',
	'title' => 'Visual settings',
	'fields' => array (
		array (
			'key' => 'field_567001f87b415',
			'label' => 'General',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'style1' => 'Header style1',
				'style2' => 'Header style2',
				'style3' => 'Header style3',
				'style4' => 'Header style4',
			),
			'default_value' => array (
				0 => 'style1',
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'field_59ccd1fa192b7',
			'label' => 'Header style',
			'name' => 'header_style',
			'type' => 'select',
			'instructions' => 'Select the style of the header',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'key' => 'field_59ce0b454581a',
			'label' => 'Header background',
			'name' => 'header_background',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_5668158ba6409',
			'label' => 'Hide breadcrumbs',
			'name' => 'hide_breadcrumbs',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_5668158badjr9',
			'label' => 'Hide featured image in posts',
			'name' => 'hide_featured_image',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_5668158badjfu',
			'label' => 'Make sidebar sticky',
			'name' => 'make_sidebar_sticky',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'post_type' => array (
				0 => 'page',
			),
			'taxonomy' => array (
			),
			'allow_null' => 1,
			'multiple' => 0,
			'allow_archives' => 0,
			'key' => 'field_59e61e59f2896',
			'label' => 'Override reviews breadcrumb link',
			'name' => 'override_reviews_breadcrumb_link',
			'type' => 'page_link',
			'instructions' => 'Select the page you want to override the default "Reviews" link in breadcrumbs.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
        array (
            'multiple' => 0,
            'allow_null' => 0,
            'choices' => array (
                'style1' => 'Review style1',
                'style2' => 'Review style2',
                'style3' => 'Review style3'
            ),
            'default_value' => array (
                0 => 'style1',
            ),
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'return_format' => 'value',
            'key' => 'field_59ccd1fa21a2',
            'label' => 'Review style',
            'name' => 'review_style',
            'type' => 'select',
            'instructions' => 'Select the style of Review',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        array (
            'multiple' => 0,
            'allow_null' => 0,
            'choices' => array (
                'style1' => 'Taxonomy Review style1',
                'style2' => 'Taxonomy Review style2',
                'style3' => 'Taxonomy Review style3',
                'style4' => 'Taxonomy Review style4',
                'style5' => 'Taxonomy Review style5'
            ),
            'default_value' => array (
                0 => 'style1',
            ),
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'return_format' => 'value',
            'key' => 'field_59cdd1fa11b4',
            'label' => 'Taxonomy Review style',
            'name' => 'taxonomy_review_style',
            'type' => 'select',
            'instructions' => 'Select the style of Review',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        array (
            'multiple' => 0,
            'allow_null' => 0,
            'choices' => array (
                'style1' => 'Category style1',
                'style2' => 'Category style2'
            ),
            'default_value' => array (
                0 => 'style1',
            ),
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'return_format' => 'value',
            'key' => 'field_59ccd1fa183s2',
            'label' => 'Category style',
            'name' => 'category_style',
            'type' => 'select',
            'instructions' => 'Select the style of Category Posts',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
		array (
			'key' => 'field_566832885d42f',
			'label' => 'Sidebar to the left',
			'name' => 'sidebar_to_the_left',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
            'default_value' => 0,
            'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_566ea18f81e60',
			'label' => 'Site logo',
			'name' => 'site_logo',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_567149cbefe9f',
			'label' => 'Logo width',
			'name' => 'logo_width',
			'type' => 'text',
			'instructions' => 'If you need your logo image to be resized enter the desired width. (For retina support for example.) If you dont want a specific width enter "auto"',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 183,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5a0073cb9be96',
			'label' => 'Logo width (mobile view)',
			'name' => 'logo_width_mobile',
			'type' => 'text',
			'instructions' => 'For the mobile view enter the desired width of the logo.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 183,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5670020c7b416',
			'label' => 'Site background color',
			'name' => 'site_background_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#f8f8f8',
		),
		array (
			'key' => 'field_566ff96da2a14',
			'label' => 'Elements radius',
			'name' => 'elements_radius',
			'type' => 'text',
			'instructions' => 'Buttons radius and other elements',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 5,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_567001e57b414',
			'label' => 'Fonts',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56a8906efdir9',
			'label' => 'Base font size',
			'name' => 'base_font_size',
			'type' => 'number',
			'instructions' => 'The base font size of the theme.<br/>Default is 14px',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 14,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_566ff136b13e0',
			'label' => 'Main font color',
			'name' => 'main_font_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#2d2d2c',
		),
		array (
			'key' => 'field_5670031b2342b',
			'label' => 'Main Font Family',
			'name' => 'font_family',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'https://fonts.googleapis.com/css?family=Rubik:300,400,400i,500,700' => 'Rubik',
				'https://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,600,700' => 'Open Sans',
				'https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300italic,400,700' => 'Open Sans Condensed',
				'https://fonts.googleapis.com/css?family=Roboto:400,300,400italic,500,700' => 'Roboto',
				'https://fonts.googleapis.com/css?family=Lato:300,400,400italic,700' => 'Lato',
				'https://fonts.googleapis.com/css?family=Oswald:300,400,700' => 'Oswald',
				'https://fonts.googleapis.com/css?family=Raleway:300,400,600,700' => 'Raleway',
				'https://fonts.googleapis.com/css?family=Ubuntu:300,400,400italic,500,700' => 'Ubuntu',
				'default' => 'Default system fonts',
			),
			'default_value' => array (
				0 => 'https://fonts.googleapis.com/css?family=Rubik:300,400,400i,500,700',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_59d75c6a3fd6e',
			'label' => 'Secondary Font Family',
			'name' => 'font_family_secondary',
			'type' => 'select',
			'instructions' => 'Font family for the headers',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'same' => 'Same as main font family',
				'https://fonts.googleapis.com/css?family=Rubik:300,400,400i,500,700' => 'Rubik',
				'https://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,600,700' => 'Open Sans',
				'https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300italic,700' => 'Open Sans Condensed',
				'https://fonts.googleapis.com/css?family=Roboto:400,300,400italic,500,700' => 'Roboto',
				'https://fonts.googleapis.com/css?family=Lato:300,400,400italic,700' => 'Lato',
				'https://fonts.googleapis.com/css?family=Oswald:300,400,700' => 'Oswald',
				'https://fonts.googleapis.com/css?family=Raleway:300,400,600,700' => 'Raleway',
                'https://fonts.googleapis.com/css?family=Ubuntu:300,400,400italic,500,700' => 'Ubuntu',
			),
			'default_value' => array (
				0 => 'same',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_566ff907a2a11',
			'label' => 'Colors',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_566ff8f4a2a10',
			'label' => 'Red color',
			'name' => 'color_red',
			'type' => 'color_picker',
			'instructions' => 'Change the red color used in the theme',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#d02d21',
		),
		array (
			'key' => 'field_566ff933a2a12',
			'label' => 'Blue color',
			'name' => 'color_blue',
			'type' => 'color_picker',
			'instructions' => 'Change the blue color used in the theme',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#2d739b',
		),
		array (
			'key' => 'field_566ff94fa2a13',
			'label' => 'Green color',
			'name' => 'color_green',
			'type' => 'color_picker',
			'instructions' => 'Change the green color used in the theme',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#559f3d',
		),
		array (
			'key' => 'field_56714250b292d',
			'label' => 'Black color',
			'name' => 'color_black',
			'type' => 'color_picker',
			'instructions' => 'Change the black color used in the theme',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#000',
		),
		array (
			'key' => 'field_59d77645b33c9',
			'label' => 'Black medium color',
			'name' => 'color_black_medium',
			'type' => 'color_picker',
			'instructions' => 'Change the medium black color used in the theme',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#181818',
		),
		array (
			'key' => 'field_59d7765117238',
			'label' => 'Black light color',
			'name' => 'color_black_light',
			'type' => 'color_picker',
			'instructions' => 'Change the light black color used in the theme',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#312f2f',
		),
		array (
			'key' => 'field_59d7765cb4d1d',
			'label' => 'Grey color',
			'name' => 'color_grey',
			'type' => 'color_picker',
			'instructions' => 'Change the black color used in the theme',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#eeedeb',
		),
		array (
			'key' => 'field_59f872af33180',
			'label' => 'AMP pages header background',
			'name' => 'amp_background_color',
			'type' => 'color_picker',
			'instructions' => 'Change color of the background on AMP pages',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#0a0a0a',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-visual-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',

));

acf_add_local_field_group(array (
	'key' => 'group_5751a1199b935',
	'title' => 'Recommended Plugins',
	'fields' => array (
		array (
			'key' => 'field_59fae093887c7',
			'label' => 'AMP',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'For AMP versions of your posts/pages/reviews first install and enable this plugin and then enable AMP option in Theme Options.
<strong>Free</strong>

<a href="'.get_admin_url().'/plugin-install.php?tab=search&s=AMP+Project+Contributors">Install Plugin</a>',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_5751a163ca5b7',
			'label' => 'Contact Form 7',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'If you want to create forms this is the most versatile form plugin with various addons available.
<strong>Free</strong>

<a href="'.get_admin_url().'/plugin-install.php?tab=search&s=Contact+form+7">Install Plugin</a>',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_5751a1a8ca5b8',
			'label' => 'AdRotate',
			'name' => 'adrotate',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'If you want to add banners to your site this is the plugin you need! Poka theme has support and you can place banners almost anywhere!
<strong>Free</strong>

<a href="'.get_admin_url().'/plugin-install.php?tab=search&s=AdRotate">Install Plugin</a>',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_5751b1053a380',
			'label' => 'Widget Importer & Exporter',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'If you want to manual import demo content with this plugin you can import the widgets from a demo.
<strong>Free</strong>

<a href="'.get_admin_url().'/plugin-install.php?tab=search&s=Widget+Importer+%26+Exporter">Install Plugin</a>',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
        ),
        array (
			'key' => 'field_5cb48795c4a4b',
			'label' => 'One Click Demo Import',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'If you want to import demo content with one click just install this plugin and follow the instructions of the documentation.
<strong>Free</strong>

<a href="'.get_admin_url().'/plugin-install.php?tab=search&s=One+Click+Demo+Import">Install Plugin</a>',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_5751b098276f2',
			'label' => 'Google Analytics Dashboard for WP',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Google Analytics statistics in your Wordpress Dashboard
<strong>Free</strong>

<a href="'.get_admin_url().'/plugin-install.php?tab=search&s=Google+Analytics+Dashboard+for+WP">Install Plugin</a>',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_576bcfbb8e4cc',
			'label' => 'Simple Custom Post Order',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Drag and drop support for posts/reviews. If you want to use the custom order for the table list shortcode leave the sort field empty.
<strong>Free</strong>

<a href="'.get_admin_url().'/plugin-install.php?tab=search&s=Simple+Custom+Post+Order">Install Plugin</a>',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_5751b02b276f1',
			'label' => 'WPML',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Multilanguage support for your site.
<strong>Paid</strong>

<a href="https://wpml.org/" target="_blank">Buy</a>',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-recommended-plugins',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_574c51491aeeb',
	'title' => 'Taxonomies fields',
	'fields' => array (
		array (
			'key' => 'field_574c515259554',
			'label' => 'Taxonomy view',
			'name' => 'taxonomy_view',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'' => 'Default style',
				'style1' => 'Style 1',
				'style2' => 'Style 2',
				'style3' => 'Style 3',
				'style4' => 'Style 4',
				'style5' => 'Style 5',
			),
			'default_value' => array (
                0 => ''
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'lists',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59d742721adfb',
	'title' => 'Category fields',
	'fields' => array (
        array (
            'multiple' => 0,
            'allow_null' => 0,
            'choices' => array (
                '' => 'Default style',
                'style1' => 'Category style1',
                'style2' => 'Category style2'
            ),
            'default_value' => array (
                0 => '',
            ),
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'return_format' => 'value',
            'key' => 'field_59d74252339c1',
            'label' => 'Category style',
            'name' => 'category_style_override',
            'type' => 'select',
            'instructions' => 'Select the style of this category',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
	),
	'location' => array (
		array (
			array (
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'category',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5c0e79fe6b5de',
	'title' => 'Translations',
	'fields' => array(
		array(
			'key' => 'field_5c0e7b8a24380',
			'label' => 'Translations information',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'By using one of the translations in this page you override the default WordPress translations used in the theme.
The theme uses the official WordPress I18n and if you want to completely translate your theme you should use the .mo/.po files inside the theme.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_5c0e7a072437e',
			'label' => 'Review post type slug',
			'name' => 'review_post_type_slug',
			'type' => 'text',
			'instructions' => 'You can change the default \'review\' slug to your own slug.<br/>
Please don\'t use white spaces and use only underscores. <br/>
After saving the options please refresh your permalinks by clicking \'Save\' to Settings/Permalinks.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c0e7b572437f',
			'label' => 'Review button text',
			'name' => 'review_button_text',
			'type' => 'text',
			'instructions' => 'You can replace all the "Review" buttons text.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c0e7c5924381',
			'label' => 'Play now button text',
			'name' => 'play_now_button_text',
			'type' => 'text',
			'instructions' => 'You can replace all the "Play now" buttons text.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c0e85b1049b5',
			'label' => 'Play button text',
			'name' => 'play_button_text',
			'type' => 'text',
			'instructions' => 'You can replace all the "Play!" buttons text.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-translations',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5d7905b58d355',
	'title' => 'Header fields',
	'fields' => array(
		array(
			'key' => 'field_5d7905c2cfc5c',
			'label' => 'Header backgound image',
			'name' => 'header_backgound_image_override',
			'type' => 'image',
			'instructions' => 'If you want a different background image from the homepage',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'affiliates',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
